version: '3.7'

services:
  queen:
    build: .
    command: python n-queen.py
    volumes:
      - .:/usr/src/app/
    depends_on: 
      - db 
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=sqlalchemy
    ports : 
      - 5432:5432

volumes:
  postgres_data: